#! /bin/bash

#   Copyright (c) 2004  Martin Schulze <joey@debian.org>
#   Copyright (c) 2006  Frank Lichtenheld <djpig@debian.org>
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

. `dirname $0`/../config.sh

logs=${topdir}/files/logs
log=${logs}/git.log

cd ${topdir}

test -d $log || mkdir -p $logs

if [ -s $log ]
then
    savelog -c 14 $log > /dev/null
fi

date > $log
git pull &> $log
date >> $log
