#! /bin/sh

. `dirname $0`/../config.sh

# Test whether all required packages are installed and generate a mail
# if they aren't, so that the admin is informed.

locales="de_DE.UTF-8 en_US.UTF-8 nl_NL fr_FR.UTF-8 uk_UA.UTF-8"

packages=`tempfile`
locs=`tempfile`
cache=`tempfile`
trap "rm -f $packages $locs" INT EXIT

cd $topdir
dpkg-checkbuilddeps >> $packages 2>&1

for l in $locales
do
    if ! grep -q "^$l" /etc/locale.gen
    then
	echo "Locale $l missing." >> $locs
	echo >> $locs
    fi
done

if [ -n "$cachedir" ]
then
    if [ ! -d "$cachedir" ]
    then
    	echo "cachedir missing." >> $cache
    else
	perm=$(ls -ld "$cachedir" | perl -ne 'print "ok" if /^drwxrws--- \d+ www-data/')
        if [ -z "$perm" ]
	then
	    echo "cachedir has wrong permissions." >> $cache
	    echo "make sure it is writable by the web server." >> $cache
	fi
    fi
fi

if [ -s $packages -o -s $locs -o -s $cache ]
then
    (
	echo "Subject: Problem packages.debian.org on `hostname -s`"
	echo "To: ${admin_email}"
	echo
	echo "On host `hostname -f`"
	echo
	if [ -s $packages ]
	then
	    echo "Missing packages:"
	    echo
	    cat $packages
	fi
	if [ -s $locs ]
	then
	    echo "Missing locales:"
	    echo
	    cat $locs
	fi
	if [ -s $cache ]
	then
	    echo "Problems with cachedir:"
	    echo
	    cat $cache
	fi
    ) | tee /dev/stderr | /usr/sbin/sendmail -t
fi
