#! /bin/sh

. `dirname $0`/../config.sh

# Test whether all required packages are installed and generate a mail
# if they aren't, so that the admin is informed.

packages=`tempfile`
cache=`tempfile`
trap "rm -f $packages $cache" INT EXIT

cd $topdir
dpkg-checkbuilddeps >> $packages 2>&1

if [ -n "$cachedir" ]
then
    if [ ! -d "$cachedir" ]
    then
    	echo "cachedir missing." >> $cache
    else
	perm=$(ls -ld "$cachedir" | perl -ne 'print "ok" if /^drwx...... \d+ www-data/ || /^d...rws... \d+ [\w-]+\/www-data/'
        if [ -z "$perm" ]
	then
	    echo "cachedir has wrong permissions." >> $cache
	    echo "make sure it is writable by the web server." >> $cache
	fi
    fi
fi

if [ -s $packages -o -s $cache ]
then
    (
	echo "Subject: Problem packages.debian.org on `hostname -s`"
	echo "To: ${admin_email}"
	echo
	echo "On host `hostname -f`"
	echo
	if [ -s $packages ]
	then
	    echo "Missing packages:"
	    echo
	    cat $packages
	fi
	if [ -s $cache ]
	then
	    echo "Problems with cachedir:"
	    echo
	    cat $cache
	fi
    ) | tee /dev/stderr | /usr/sbin/sendmail -t
fi
