#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
arch=m68k
if [ -z "${localdir}" ]
then
    echo using remote mirror
    for dist in etch
    do
        echo "retrieve Release(.gpg) $dist"
	test -d us/${dist}-${arch} || mkdir -p us/${dist}-${arch}
	(cd us/${dist} &&
	    $wget_cmd -N ${ftpsite}/dists/${dist}-${arch}/Release &&
	    $wget_cmd -N ${ftpsite}/dists/${dist}-${arch}/Release.gpg )
        
#	foo=\$arch_${dist//-/_}
#	for arch in `eval echo $foo`
#	do
	    for part in ${parts}
	    do
	        echo retrieve Packages $dist-${arch}/$part/$arch
		test -d us/${dist}-${arch}/${part}/binary-${arch} || mkdir -p us/${dist}-${arch}/${part}/binary-${arch}
		(cd us/${dist}-${arch}/${part}/binary-${arch} &&
		    $wget_cmd -N ${ftpsite}/dists/${dist}-${arch}/${part}/binary-${arch}/Packages.gz)
	    done
	    #FIXME: no Contents files for p-u
	    test ! "$dist" = "experimental" || continue
	    echo retrieve Contents $dist/$arch
	    (cd us/${dist}-${arch} &&
		$wget_cmd -N ${ftpsite}/dists/${dist}-${arch}/Contents-${arch}.gz)
#	done
	for part in ${parts}
	do
	    echo retrieve Sources $dist-${arch}/$part
	    test -d us/${dist}-${arch}/${part}/source || mkdir -p us/${dist}-${arch}/${part}/source
            (cd us/${dist}-${arch}/${part}/source &&
                $wget_cmd -N ${ftpsite}/dists/${dist}-${arch}/${part}/source/Sources.gz)
	done
    done
else
    echo using local mirror
    for dist in etch
    do
        echo "retrieve Releases(.gpg) $dist"
	test -d us/${dist}-${arch} || mkdir -p us/${dist}-${arch}
	(cd us/${dist}-${arch} &&
	    rsync -t ${localdir}/dists/${dist}-${arch}/Release &&
	    rsync -t ${localdir}/dists/${dist}-${arch}/Release.gpg )

#	foo=\$arch_${dist//-/_}
#	for arch in `eval echo $foo`
#	do
	    for part in ${parts}
	    do
	        echo retrieve Packages $dist-${arch}/$part/$arch
		test -d us/${dist}-${arch}/${part}/binary-${arch} || mkdir -p us/${dist}-${arch}/${part}/binary-${arch}
		rsync -t ${localdir}/dists/${dist}-${arch}/${part}/binary-${arch}/Packages.gz \
		    us/${dist}-${arch}/${part}/binary-${arch}/Packages.gz
	    done
	    #FIXME: no Contents files for p-u
	    test ! "$dist" = "experimental" || continue
	    echo retrieve Contents $dist-${arch}/$arch
	    rsync -t ${localdir}/dists/${dist}-${arch}/Contents-${arch}.gz \
		us/${dist}-${arch}/Contents-${arch}.gz
#	done
	for part in ${parts}
        do
	    echo retrieve Sources $dist-${arch}/$part
            test -d us/${dist}-${arch}/${part}/source || mkdir -p us/${dist}-${arch}/${part}/source
            rsync -t ${localdir}/dists/${dist}-${arch}/${part}/source/Sources.gz \
	    	us/${dist}-${arch}/${part}/source/Sources.gz
	done
    done
fi

