#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
if [ -z "${localdir}" ]
then
    echo using remote mirror
    for dist in $dists
    do
        echo "retrieve Release(.gpg) $dist"
	test -d us/${dist} || mkdir -p us/${dist}
	(cd us/${dist} &&
	    $wget_cmd -N ${ftpsite}/dists/${dist}/Release &&
	    $wget_cmd -N ${ftpsite}/dists/${dist}/Release.gpg )
        
	foo=\$arch_${dist//-/_}
	for arch in `eval echo $foo`
	do
	    test ! "$arch" = "kfreebsd-i386" || continue
	    test ! "$arch" = "kfreebsd-amd64" || continue
	    for part in ${parts}
	    do
	        echo retrieve Packages $dist/$part/$arch
		test -d us/${dist}/${part}/binary-${arch} || mkdir -p us/${dist}/${part}/binary-${arch}
		(cd us/${dist}/${part}/binary-${arch} &&
		    $wget_cmd -N ${ftpsite}/dists/${dist}/${part}/binary-${arch}/Packages.gz)
	    done
	    #FIXME: no Contents files for p-u
	    test ! "$dist" = "experimental" || continue
	    echo retrieve Contents $dist/$arch
	    (cd us/${dist} &&
		$wget_cmd -N ${ftpsite}/dists/${dist}/Contents-${arch}.gz)
	done
	for part in ${parts}
	do
	    echo retrieve Sources $dist/$part
	    test -d us/${dist}/${part}/source || mkdir -p us/${dist}/${part}/source
            (cd us/${dist}/${part}/source &&
                $wget_cmd -N ${ftpsite}/dists/${dist}/${part}/source/Sources.gz)
	done

	$check_release_cmd $archivedir/us/${dist}/Release
    done
else
    echo using local mirror
    for dist in $dists
    do
        echo "retrieve Releases(.gpg) $dist"
	test -d us/${dist} || mkdir -p us/${dist}
	rsync -t ${localdir}/dists/${dist}/Release us/${dist}/Release
	rsync -t ${localdir}/dists/${dist}/Release.gpg us/${dist}/Release.gpg

	foo=\$arch_${dist//-/_}
	for arch in `eval echo $foo`
	do
	    test ! "$arch" = "kfreebsd-i386" || continue
	    test ! "$arch" = "kfreebsd-amd64" || continue
	    for part in ${parts}
	    do
	        echo retrieve Packages $dist/$part/$arch
		test -d us/${dist}/${part}/binary-${arch} || mkdir -p us/${dist}/${part}/binary-${arch}
		rsync -t ${localdir}/dists/${dist}/${part}/binary-${arch}/Packages.gz \
		    us/${dist}/${part}/binary-${arch}/Packages.gz
	    done
	    #FIXME: no Contents files for p-u
	    test ! "$dist" = "experimental" || continue
	    echo retrieve Contents $dist/$arch
	    rsync -t ${localdir}/dists/${dist}/Contents-${arch}.gz \
		us/${dist}/Contents-${arch}.gz
	done
	for part in ${parts}
        do
	    echo retrieve Sources $dist/$part
            test -d us/${dist}/${part}/source || mkdir -p us/${dist}/${part}/source
            rsync -t ${localdir}/dists/${dist}/${part}/source/Sources.gz \
	    	us/${dist}/${part}/source/Sources.gz
	done

	$check_release_cmd $archivedir/us/${dist}/Release
    done
fi
