#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
if [ -z "${localdir}" ]
then
    echo using remote mirror
    for dist in ${dists}
    do

	foo=\$arch_${dist//-/_}
	for arch in `eval echo $foo`
	do
	    for part in $parts
	    do
		part="$part/debian-installer"
	        echo retrieve Packages $dist/$part/$arch
		test -d us/${dist}/${part}/binary-${arch} || mkdir -p us/${dist}/${part}/binary-${arch}
		(cd us/${dist}/${part}/binary-${arch} &&
		    $wget_cmd -N ${ftpsite}/dists/${dist}/${part}/binary-${arch}/Packages.gz)
	    done
	done

	$check_release_cmd $archivedir/us/${dist}/Release
    done
else
    echo using local mirror
    for dist in ${dists}
    do

	foo=\$arch_${dist//-/_}
	for arch in `eval echo $foo`
	do
	    for part in $parts
	    do
		part="$part/debian-installer"
	        echo retrieve Sources $dist/$part/$arch
		test -d us/${dist}/${part}/binary-${arch} || mkdir -p us/${dist}/${part}/binary-${arch}
		rsync -Lt ${localdir}/dists/${dist}/${part}/binary-${arch}/Packages.gz \
		    us/${dist}/${part}/binary-${arch}/Packages.gz
	    done
	done

	$check_release_cmd $archivedir/us/${dist}/Release
    done
fi
