#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
architectures="kfreebsd-i386 kfreebsd-amd64"

for arch in $architectures
  do
  for dist in unstable experimental
    do
    for part in ${parts} main/debian-installer
      do
      echo retrieve Packages $dist/$part/$arch
      test -d kfreebsd/${dist}/${part}/binary-${arch} || mkdir -p kfreebsd/${dist}/${part}/binary-${arch}
      (cd kfreebsd/${dist}/${part}/binary-${arch} &&
	  wget -q -N ${kfreebsd_ftpsite}/dists/${dist}/${part}/binary-${arch}/Packages.gz)
    done
    echo retrieve Contents $dist/$arch
    (cd kfreebsd/${dist} &&
	wget -q -N ${kfreebsd_ftpsite}/dists/${dist}/Contents-${arch}.gz)
  done
done
