#!/bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# volatile archive
#
for dist in stable
do
    foo=\$arch_${dist//-/_}
    for arch in `eval echo $foo`
    do
      for part in ${parts}
      do
	echo retrieve Packages $dist/$part/volatile/$arch
	test -d volatile/${dist}-volatile/${part}/binary-${arch} || mkdir -p volatile/${dist}-volatile/${part}/binary-${arch}
	(cd  volatile/${dist}-volatile/${part}/binary-${arch} &&
	    wget -q -N ${volatile_ftpsite}/dists/${dist}/volatile/${part}/binary-${arch}/Packages.gz)
      done
    done
    for part in ${parts}
    do
        echo retrieve Sources $dist/$part/volatile
        test -d volatile/${dist}-volatile/${part}/source || mkdir -p volatile/${dist}-volatile/${part}/source
        (cd volatile/${dist}/${part}-volatile/source &&
            wget -q -N ${volatile_ftpsite}/dists/${dist}/volatile/${part}/source/Sources.gz)
    done
done
