#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# scp -q auric:/org/ftp.debian.org/ftp/indices/Maintainers .

if [ -f /org/ftp.root/debian/indices/Maintainers ]
then
    if [ ! -s Maintainers -a -L Maintainers ]
    then
	ln -s /org/ftp.root/debian/indices/Maintainers .
    fi
else
    if [ ! -L Maintainers ]
    then
	$wget_cmd -O Maintainers $ftpsite/indices/Maintainers
    fi
fi
