#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
architectures=${arch_debports}

for dist in ${suites}
  do
  echo "retrieve Release(.gpg) $dist"
  test -d ports/${dist} || mkdir -p ports/${dist}
  (cd ports/${dist} &&
	    $wget_cmd -N ${debports_ftpsite}/dists/${dist}/Release &&
	    $wget_cmd -N ${debports_ftpsite}/dists/${dist}/Release.gpg )

  for arch in $architectures
    do
    for part in ${parts} main/debian-installer
      do
      echo retrieve Packages $dist/$part/$arch
      test -d ports/${dist}/${part}/binary-${arch} || mkdir -p ports/${dist}/${part}/binary-${arch}
      (cd ports/${dist}/${part}/binary-${arch} &&
	  $wget_cmd -N ${debports_ftpsite}/dists/${dist}/${part}/binary-${arch}/Packages.gz)
    done
    echo retrieve Contents $dist/$arch
    (cd ports/${dist} &&
	$wget_cmd -N ${debports_ftpsite}/dists/${dist}/Contents-${arch}.gz)
  done

  $check_release_cmd $archivedir/ports/${dist}/Release
done
