#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
if [ -z "${localdir}" ]
then
    echo using remote mirror
    for dist in $dists
    do
        echo "retrieve Release(.gpg) $dist"
	test -d us/${dist} || mkdir -p us/${dist}
	(cd us/${dist} &&
	    $wget_cmd -N ${ftpsite}/dists/${dist}/Release &&
	    $wget_cmd -N ${ftpsite}/dists/${dist}/Release.gpg )
        
	foo=\$arch_${dist//-/_}
	for arch in `eval echo $foo`
	do
	    for part in ${parts}
	    do
	        echo retrieve Packages $dist/$part/$arch
		test -d us/${dist}/${part}/binary-${arch} || mkdir -p us/${dist}/${part}/binary-${arch}
		(cd us/${dist}/${part}/binary-${arch} &&
		    $wget_cmd -N ${ftpsite}/dists/${dist}/${part}/binary-${arch}/Packages.gz)
	    done
	    #FIXME: no Contents files for p-u
	    echo retrieve Contents $dist/$arch
	    (cd us/${dist} &&
		$wget_cmd -N ${ftpsite}/dists/${dist}/Contents-${arch}.gz)
	done
	for part in ${parts}
	do
	    echo retrieve Sources $dist/$part
	    test -d us/${dist}/${part}/source || mkdir -p us/${dist}/${part}/source
            (cd us/${dist}/${part}/source &&
                $wget_cmd -N ${ftpsite}/dists/${dist}/${part}/source/Sources.gz)
	done

	$check_release_cmd $archivedir/us/${dist}/Release
    done
else
    echo using local mirror
    for dist in $dists
    do
        echo "retrieve Releases(.gpg) $dist"
	test -d us/${dist} || mkdir -p us/${dist}
	rsync -Lt ${localdir}/dists/${dist}/Release us/${dist}/Release
	rsync -Lt ${localdir}/dists/${dist}/Release.gpg us/${dist}/Release.gpg

	foo=\$arch_${dist//-/_}
	for arch in `eval echo $foo`
	do
	    for part in ${parts}
	    do
	        echo retrieve Packages $dist/$part/$arch
		test -d us/${dist}/${part}/binary-${arch} || mkdir -p us/${dist}/${part}/binary-${arch}
		rsync -Lt ${localdir}/dists/${dist}/${part}/binary-${arch}/Packages.gz \
		    us/${dist}/${part}/binary-${arch}/Packages.gz
	    done
	    #FIXME: no Contents files for p-u
	    #FIXME: the symlinks for wheezy/sid/experimental will go away
	    #FIXME: this only pulls in the contents files for main in wheezy/sid/experimental
	    echo retrieve Contents $dist/$arch
	    rsync -Lt ${localdir}/dists/${dist}/Contents-${arch}.gz \
		us/${dist}/Contents-${arch}.gz
	done
	for part in ${parts}
        do
	    echo retrieve Sources $dist/$part
            test -d us/${dist}/${part}/source || mkdir -p us/${dist}/${part}/source
            rsync -Lt ${localdir}/dists/${dist}/${part}/source/Sources.gz \
	    	us/${dist}/${part}/source/Sources.gz
	done

	$check_release_cmd $archivedir/us/${dist}/Release
    done
fi

# security archive
#
for dist in squeeze wheezy
do
    echo "retrieve Release(.gpg) $dist"
    test -d security/${dist} || mkdir -p security/${dist}
    (cd security/${dist} &&
	$wget_cmd -N ${security_ftpsite}/dists/${dist}/updates/Release &&
	$wget_cmd -N ${security_ftpsite}/dists/${dist}/updates/Release.gpg )
        
    foo=\$arch_${dist//-/_}
    for arch in `eval echo $foo`
    do
      for part in ${parts}
      do
	echo retrieve Packages $dist/$part/security/$arch
	test -d security/${dist}/${part}/binary-${arch} || mkdir -p security/${dist}/${part}/binary-${arch}
	(cd  security/${dist}/${part}/binary-${arch} &&
	    $wget_cmd -N ${security_ftpsite}/dists/${dist}/updates/${part}/binary-${arch}/Packages.gz)
      done
    done
    for part in ${parts}
    do
        echo retrieve Sources $dist/$part/security
        test -d security/${dist}/${part}/source || mkdir -p security/${dist}/${part}/source
        (cd security/${dist}/${part}/source &&
            $wget_cmd -N ${security_ftpsite}/dists/${dist}/updates/${part}/source/Sources.gz)
    done

    $check_release_cmd $archivedir/security/${dist}/Release
done
