#! /bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# Main archive
#
architectures="armel kfreebsd-i386 kfreebsd-amd64"

for dist in unstable experimental
  do
  echo "retrieve Release(.gpg) $dist"
  test -d gnuab/${dist} || mkdir -p gnuab/${dist}
  (cd gnuab/${dist} &&
	    wget -q -N ${gnuab_ftpsite}/dists/${dist}/Release &&
	    wget -q -N ${gnuab_ftpsite}/dists/${dist}/Release.gpg )

  for arch in $architectures
    do
    for part in ${parts} main/debian-installer
      do
      echo retrieve Packages $dist/$part/$arch
      test -d gnuab/${dist}/${part}/binary-${arch} || mkdir -p gnuab/${dist}/${part}/binary-${arch}
      (cd gnuab/${dist}/${part}/binary-${arch} &&
	  wget -q -N ${gnuab_ftpsite}/dists/${dist}/${part}/binary-${arch}/Packages.gz)
    done
    echo retrieve Contents $dist/$arch
    (cd gnuab/${dist} &&
	wget -q -N ${gnuab_ftpsite}/dists/${dist}/Contents-${arch}.gz)
  done
done
