#!/bin/bash

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

# volatile archive
#
for dist in stable
do
    foo=\$arch_${dist//-/_}
    for arch in `eval echo $foo`
    do
      for part in ${parts}
      do
	echo retrieve Packages $dist-volatile/$part/$arch
	test -d us/${dist}-volatile/${part}/binary-${arch} || mkdir -p us/${dist}-volatile/${part}/binary-${arch}
	(cd  us/${dist}-volatile/${part}/binary-${arch} &&
	    wget -q -N ${volatile_ftpsite}/dists/${dist}/volatile/${part}/binary-${arch}/Packages.gz)
      done
    done
    for part in ${parts}
    do
        echo retrieve Sources $dist-volatile/$part
        test -d us/${dist}-volatile/${part}/source || mkdir -p us/${dist}-volatile/${part}/source
        (cd us/${dist}-volatile/$part/source &&
            wget -q -N ${volatile_ftpsite}/dists/${dist}/volatile/${part}/source/Sources.gz)
    done
done
