#! /bin/bash

. `dirname $0`/../config.sh

debtagsdir="$filesdir/debtags"

test -d ${debtagsdir} || mkdir -p ${debtagsdir}
cd ${debtagsdir}

$wget_cmd -N https://anonscm.debian.org/git/debtags/vocabulary.git/plain/debian-packages

cd "$topdir"

./bin/parse-debtags-voc
