#! /bin/bash

. `dirname $0`/../config.sh

debtagsdir="$filesdir/debtags"

test -d ${debtagsdir} || mkdir -p ${debtagsdir}
cd ${debtagsdir}

export http_proxy=http://squid.external:3128/
$wget_cmd -N http://debtags.alioth.debian.org/tags/vocabulary.gz &&
	gunzip -f vocabulary.gz

cd "$topdir"

./bin/parse-debtags-voc
