#! /bin/bash

. `dirname $0`/../config.sh

debtagsdir="$filesdir/debtags"

test -d ${debtagsdir} || mkdir -p ${debtagsdir}
cd ${debtagsdir}

$wget_cmd -N https://salsa.debian.org/debtags-team/debtags-vocabulary/raw/master/debian-packages

cd "$topdir"

./bin/parse-debtags-voc
