#! /bin/sh

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

if [ -z "${localdir}" ] || [ -n "$ddtp_ftpsite" ]
then
    if [ -z "$ddtp_ftpsite" ]
    then
	ddtp_ftpsite="$ftpsite"
    fi
    echo using remote mirror $ddtp_ftpsite
    for dist in sid
    do
	for part in main
	do
	  test -d us/${dist}/${part}/i18n || mkdir -p us/${dist}/${part}/i18n
	  for lang in $ddtplangs
	  do
	    locale=$(echo $lang|perl -p -e 's/^([a-z]{2})-([a-z]{2})$/"$1_".uc($2)/e')
	    echo "retrieve translated Descs $dist/$part/$lang ($locale)"
            (cd us/${dist}/${part}/i18n &&
                $wget_cmd -N ${ddtp_ftpsite}/dists/${dist}/${part}/i18n/Translation-$locale.bz2)
	  done
	done
    done
else
    echo using local mirror
    for dist in sid
    do
	for part in main
	do
	  test -d us/${dist}/${part}/i18n || mkdir -p us/${dist}/${part}/i18n
	  for lang in $ddtplangs
	  do
	    locale=$(echo $lang|perl -p -e 's/^([a-z]{2})-([a-z]{2})$/"$1_".uc($2)/e')
	    echo "retrieve translated Descs $dist/$part/$lang ($locale)"
            rsync -Lt ${localdir}/dists/${dist}/${part}/i18n/Translation-$locale.bz2 \
	    	us/${dist}/${part}/i18n/Translation-$locale.bz2
	  done
	done
    done
fi

exit 0
