#! /bin/sh

. `dirname $0`/../config.sh

test -d ${archivedir} || mkdir -p ${archivedir}
cd ${archivedir}

if [ -z "${localdir}" ]
then
    echo using remote mirror
    for dist in sid
    do
	for part in main
	do
	  test -d us/${dist}/${part}/i18n || mkdir -p us/${dist}/${part}/i18n
	  for lang in $ddtplangs
	  do
	    echo retrieve translated Descs $dist/$part/$lang
            (cd us/${dist}/${part}/i18n &&
                wget -q -N ${ftpsite}/dists/${dist}/${part}/i18n/Translations-$lang.gz)
	  done
	done
    done
else
    echo using local mirror
    for dist in sid
    do
	for part in main
	do
	  test -d us/${dist}/${part}/i18n || mkdir -p us/${dist}/${part}/i18n
	  for lang in $ddtplangs
	  do
	    echo retrieve translated Descs $dist/$part/$lang
            rsync -t ${localdir}/dists/${dist}/${part}/i18n/Translation-$lang.gz \
	    	us/${dist}/${part}/i18n/Translation-$lang.gz
	  done
	done
    done
fi
