#! /bin/bash

. `dirname $0`/../config.sh

isodate=$(date -I)
packagesdir="${filesdir}/packages/${isodate}"
test -d "${packagesdir}" || mkdir -p "${packagesdir}"

cd $topdir
for dist in $dists
do
    echo newpkg info for $dist
    LANG=C cat "${filesdir}/db/package_names_${dist}.txt" \
	| sort | uniq > "${packagesdir}/package_names_${dist}"
    LANG=C cat "${filesdir}/db/source_names_${dist}.txt" \
	| sort | uniq > "${packagesdir}/source_names_${dist}"

    ./bin/newpkg_info ${dist}
done
